//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V8Sargsyan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class V8SargsyanEntities : DbContext
    {
        public V8SargsyanEntities()
            : base("name=V8SargsyanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Executor> Executors { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<WorkType> WorkTypes { get; set; }
    }
}
