//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V8Sargsyan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int ID { get; set; }
        public Nullable<int> Менеджер { get; set; }
        public Nullable<decimal> Middle__мин_ЗП_ { get; set; }
        public Nullable<decimal> Senior__мин_ЗП_ { get; set; }
        public Nullable<double> Коэффициент_для_Анализ_и_проектирование { get; set; }
        public Nullable<double> Коэффициент_для_Установка_оборудования { get; set; }
        public Nullable<double> Коэффициент_для_Техническое_обслуживание_и_сопровождение { get; set; }
        public Nullable<int> Коэффициент_сложности { get; set; }
        public Nullable<int> Коэффициент_Времени { get; set; }
        public Nullable<int> Коэффициент_Денег { get; set; }
        public Nullable<decimal> Junior { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
