//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V8Sargsyan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public Nullable<int> Исполнитель { get; set; }
        public string Заголовок { get; set; }
        public Nullable<double> Сложность { get; set; }
        public Nullable<int> Статус { get; set; }
        public Nullable<int> Характер_работы { get; set; }
    
        public virtual Executor Executor { get; set; }
        public virtual Status Status { get; set; }
        public virtual WorkType WorkType { get; set; }
    }
}
